# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/code/e_design/SoC/MiniMIPS32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_top_0_0_1/design_1_top_0_0.xci
# IP: The module: 'design_1_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/code/e_design/SoC/MiniMIPS32_Lite_FullSyS.srcs/sources_1/ip/data_ram/data_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==data_ram || ORIG_REF_NAME==data_ram} -quiet] -quiet

# IP: D:/code/e_design/SoC/MiniMIPS32_Lite_FullSyS.srcs/sources_1/ip/inst_rom/inst_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==inst_rom || ORIG_REF_NAME==inst_rom} -quiet] -quiet

# XDC: d:/code/e_design/SoC/MiniMIPS32_Lite_FullSyS.srcs/sources_1/ip/data_ram/data_ram_ooc.xdc

# XDC: d:/code/e_design/SoC/MiniMIPS32_Lite_FullSyS.srcs/sources_1/ip/inst_rom/inst_rom_ooc.xdc

# XDC: d:/code/e_design/SoC/MiniMIPS32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_top_0_0_1/design_1_top_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_top_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/code/e_design/SoC/MiniMIPS32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_top_0_0_1/design_1_top_0_0.xci
# IP: The module: 'design_1_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/code/e_design/SoC/MiniMIPS32_Lite_FullSyS.srcs/sources_1/ip/data_ram/data_ram.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==data_ram || ORIG_REF_NAME==data_ram} -quiet] -quiet

# IP: D:/code/e_design/SoC/MiniMIPS32_Lite_FullSyS.srcs/sources_1/ip/inst_rom/inst_rom.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==inst_rom || ORIG_REF_NAME==inst_rom} -quiet] -quiet

# XDC: d:/code/e_design/SoC/MiniMIPS32_Lite_FullSyS.srcs/sources_1/ip/data_ram/data_ram_ooc.xdc

# XDC: d:/code/e_design/SoC/MiniMIPS32_Lite_FullSyS.srcs/sources_1/ip/inst_rom/inst_rom_ooc.xdc

# XDC: d:/code/e_design/SoC/MiniMIPS32_Lite_FullSyS.srcs/sources_1/bd/design_1/ip/design_1_top_0_0_1/design_1_top_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_top_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
